services:
  - type: web
    runtime: go
    name: tracking-pixel
    repo: https://github.com/unra73d/tracking-pixel
    branch: main
    buildCommand: go mod tidy && go build -o main main.go
    startCommand: ./main
    autoDeploy: true
    plan: free