previews:
  generation: automatic

services:
  - type: web
    runtime: go
    name: tracking-pixel
    repo: https://github.com/unra73d/tracking-pixel
    branch: main
    buildCommand: go buid main.go main
    startCommand: ./main
    autoDeploy: true